
export const GET_DATABYTOKEN_REQUEST = "GET_DATABYTOKEN_REQUEST"
export const GET_DATABYTOKEN_SUCCESS = "GET_DATABYTOKEN_SUCCESS"
export const GET_DATABYTOKEN_FAILURE  = "GET_DATABYTOKEN_FAILURE"


export const GET_DATABYPAIR_REQUEST = "GET_DATABYPAIR_REQUEST"
export const GET_DATABYPAIR_SUCCESS = "GET_DATABYPAIR_SUCCESS"
export const GET_DATABYPAIR_FAILURE = "GET_DATABYPAIR_FAILURE"